version: '3'

services:    
  webapi:
    image: webapi:latest
    build:
      context: .
      dockerfile: ../src/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - docker-RabbitMQ.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    container_name: postgresql-db
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - docker-postgres-db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  postgres_data:
